/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    bowlingRating: bigint;
    name: string;
    battingRating: bigint;
}
export interface MatchResult {
    overs: bigint;
    wonToss: string;
    runs: bigint;
    remainingBalls: bigint;
    winner: string;
    ballsPlayed: bigint;
    wickets: bigint;
    batFirst: string;
}
export interface MatchState {
    result?: MatchResult;
    totalOvers: bigint;
    isOver: boolean;
    wicketsLost: bigint;
    currentOver: bigint;
    matchId: MatchId;
    runsScored: bigint;
    format: MatchFormat;
}
export type MatchId = bigint;
export interface UserProfile {
    name: string;
}
export interface Team {
    name: string;
    countryCode: string;
    jerseyColor: string;
    squad: Array<Player>;
}
export enum MatchFormat {
    odi = "odi",
    t20 = "t20",
    test = "test"
}
export enum TournamentType {
    bbl = "bbl",
    ipl = "ipl",
    ranjiTrophy = "ranjiTrophy",
    countyChampionship = "countyChampionship",
    sheffieldShield = "sheffieldShield"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addTeam(name: string, code: string, color: string, players: Array<Player>): Promise<void>;
    addTournamentTeam(tournamentType: TournamentType, team: Team): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearMatches(): Promise<void>;
    clearTeams(): Promise<void>;
    createMatch(format: MatchFormat, isOver: boolean, totalOvers: bigint, currentOver: bigint, runsScored: bigint, wicketsLost: bigint, result: MatchResult | null): Promise<MatchId>;
    getAllMatches(): Promise<Array<MatchState>>;
    getAllTeams(): Promise<Array<Team>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMatch(matchId: MatchId): Promise<MatchState | null>;
    getTeamByName(name: string): Promise<Team | null>;
    getTournamentMatches(tournamentType: TournamentType): Promise<Array<MatchResult>>;
    getTournamentTeams(tournamentType: TournamentType): Promise<Array<Team>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    recordTournamentResult(tournamentType: TournamentType, result: MatchResult): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { MatchFormat as _MatchFormat, MatchId as _MatchId, MatchResult as _MatchResult, MatchState as _MatchState, Team as _Team, TournamentType as _TournamentType, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addTeam(arg0: string, arg1: string, arg2: string, arg3: Array<Player>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTournamentTeam(arg0: TournamentType, arg1: Team): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTournamentTeam(to_candid_TournamentType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTournamentTeam(to_candid_TournamentType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearMatches(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMatches();
            return result;
        }
    }
    async clearTeams(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearTeams();
            return result;
        }
    }
    async createMatch(arg0: MatchFormat, arg1: boolean, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: MatchResult | null): Promise<MatchId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(to_candid_MatchFormat_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(to_candid_MatchFormat_n5(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async getAllMatches(): Promise<Array<MatchState>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeams(): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: MatchId): Promise<MatchState | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeamByName(arg0: string): Promise<Team | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamByName(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamByName(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTournamentMatches(arg0: TournamentType): Promise<Array<MatchResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentMatches(to_candid_TournamentType_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentMatches(to_candid_TournamentType_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getTournamentTeams(arg0: TournamentType): Promise<Array<Team>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTournamentTeams(to_candid_TournamentType_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTournamentTeams(to_candid_TournamentType_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async recordTournamentResult(arg0: TournamentType, arg1: MatchResult): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTournamentResult(to_candid_TournamentType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTournamentResult(to_candid_TournamentType_n1(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_MatchFormat_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchFormat): MatchFormat {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_MatchState_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchState): MatchState {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchResult]): MatchResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MatchState]): MatchState | null {
    return value.length === 0 ? null : from_candid_MatchState_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Team]): Team | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: [] | [_MatchResult];
    totalOvers: bigint;
    isOver: boolean;
    wicketsLost: bigint;
    currentOver: bigint;
    matchId: _MatchId;
    runsScored: bigint;
    format: _MatchFormat;
}): {
    result?: MatchResult;
    totalOvers: bigint;
    isOver: boolean;
    wicketsLost: bigint;
    currentOver: bigint;
    matchId: MatchId;
    runsScored: bigint;
    format: MatchFormat;
} {
    return {
        result: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.result)),
        totalOvers: value.totalOvers,
        isOver: value.isOver,
        wicketsLost: value.wicketsLost,
        currentOver: value.currentOver,
        matchId: value.matchId,
        runsScored: value.runsScored,
        format: from_candid_MatchFormat_n12(_uploadFile, _downloadFile, value.format)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    odi: null;
} | {
    t20: null;
} | {
    test: null;
}): MatchFormat {
    return "odi" in value ? MatchFormat.odi : "t20" in value ? MatchFormat.t20 : "test" in value ? MatchFormat.test : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MatchState>): Array<MatchState> {
    return value.map((x)=>from_candid_MatchState_n9(_uploadFile, _downloadFile, x));
}
function to_candid_MatchFormat_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchFormat): _MatchFormat {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TournamentType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentType): _TournamentType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchResult | null): [] | [_MatchResult] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TournamentType): {
    bbl: null;
} | {
    ipl: null;
} | {
    ranjiTrophy: null;
} | {
    countyChampionship: null;
} | {
    sheffieldShield: null;
} {
    return value == TournamentType.bbl ? {
        bbl: null
    } : value == TournamentType.ipl ? {
        ipl: null
    } : value == TournamentType.ranjiTrophy ? {
        ranjiTrophy: null
    } : value == TournamentType.countyChampionship ? {
        countyChampionship: null
    } : value == TournamentType.sheffieldShield ? {
        sheffieldShield: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MatchFormat): {
    odi: null;
} | {
    t20: null;
} | {
    test: null;
} {
    return value == MatchFormat.odi ? {
        odi: null
    } : value == MatchFormat.t20 ? {
        t20: null
    } : value == MatchFormat.test ? {
        test: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
