/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Player = IDL.Record({
  'bowlingRating' : IDL.Int,
  'name' : IDL.Text,
  'battingRating' : IDL.Int,
});
export const TournamentType = IDL.Variant({
  'bbl' : IDL.Null,
  'ipl' : IDL.Null,
  'ranjiTrophy' : IDL.Null,
  'countyChampionship' : IDL.Null,
  'sheffieldShield' : IDL.Null,
});
export const Team = IDL.Record({
  'name' : IDL.Text,
  'countryCode' : IDL.Text,
  'jerseyColor' : IDL.Text,
  'squad' : IDL.Vec(Player),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchFormat = IDL.Variant({
  'odi' : IDL.Null,
  't20' : IDL.Null,
  'test' : IDL.Null,
});
export const MatchResult = IDL.Record({
  'overs' : IDL.Int,
  'wonToss' : IDL.Text,
  'runs' : IDL.Int,
  'remainingBalls' : IDL.Int,
  'winner' : IDL.Text,
  'ballsPlayed' : IDL.Int,
  'wickets' : IDL.Int,
  'batFirst' : IDL.Text,
});
export const MatchId = IDL.Nat;
export const MatchState = IDL.Record({
  'result' : IDL.Opt(MatchResult),
  'totalOvers' : IDL.Int,
  'isOver' : IDL.Bool,
  'wicketsLost' : IDL.Int,
  'currentOver' : IDL.Int,
  'matchId' : MatchId,
  'runsScored' : IDL.Int,
  'format' : MatchFormat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Player)], [], []),
  'addTournamentTeam' : IDL.Func([TournamentType, Team], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMatches' : IDL.Func([], [], []),
  'clearTeams' : IDL.Func([], [], []),
  'createMatch' : IDL.Func(
      [
        MatchFormat,
        IDL.Bool,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Int,
        IDL.Opt(MatchResult),
      ],
      [MatchId],
      [],
    ),
  'getAllMatches' : IDL.Func([], [IDL.Vec(MatchState)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([MatchId], [IDL.Opt(MatchState)], ['query']),
  'getTeamByName' : IDL.Func([IDL.Text], [IDL.Opt(Team)], ['query']),
  'getTournamentMatches' : IDL.Func(
      [TournamentType],
      [IDL.Vec(MatchResult)],
      ['query'],
    ),
  'getTournamentTeams' : IDL.Func([TournamentType], [IDL.Vec(Team)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordTournamentResult' : IDL.Func([TournamentType, MatchResult], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Player = IDL.Record({
    'bowlingRating' : IDL.Int,
    'name' : IDL.Text,
    'battingRating' : IDL.Int,
  });
  const TournamentType = IDL.Variant({
    'bbl' : IDL.Null,
    'ipl' : IDL.Null,
    'ranjiTrophy' : IDL.Null,
    'countyChampionship' : IDL.Null,
    'sheffieldShield' : IDL.Null,
  });
  const Team = IDL.Record({
    'name' : IDL.Text,
    'countryCode' : IDL.Text,
    'jerseyColor' : IDL.Text,
    'squad' : IDL.Vec(Player),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchFormat = IDL.Variant({
    'odi' : IDL.Null,
    't20' : IDL.Null,
    'test' : IDL.Null,
  });
  const MatchResult = IDL.Record({
    'overs' : IDL.Int,
    'wonToss' : IDL.Text,
    'runs' : IDL.Int,
    'remainingBalls' : IDL.Int,
    'winner' : IDL.Text,
    'ballsPlayed' : IDL.Int,
    'wickets' : IDL.Int,
    'batFirst' : IDL.Text,
  });
  const MatchId = IDL.Nat;
  const MatchState = IDL.Record({
    'result' : IDL.Opt(MatchResult),
    'totalOvers' : IDL.Int,
    'isOver' : IDL.Bool,
    'wicketsLost' : IDL.Int,
    'currentOver' : IDL.Int,
    'matchId' : MatchId,
    'runsScored' : IDL.Int,
    'format' : MatchFormat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTeam' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(Player)],
        [],
        [],
      ),
    'addTournamentTeam' : IDL.Func([TournamentType, Team], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMatches' : IDL.Func([], [], []),
    'clearTeams' : IDL.Func([], [], []),
    'createMatch' : IDL.Func(
        [
          MatchFormat,
          IDL.Bool,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Int,
          IDL.Opt(MatchResult),
        ],
        [MatchId],
        [],
      ),
    'getAllMatches' : IDL.Func([], [IDL.Vec(MatchState)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(Team)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([MatchId], [IDL.Opt(MatchState)], ['query']),
    'getTeamByName' : IDL.Func([IDL.Text], [IDL.Opt(Team)], ['query']),
    'getTournamentMatches' : IDL.Func(
        [TournamentType],
        [IDL.Vec(MatchResult)],
        ['query'],
      ),
    'getTournamentTeams' : IDL.Func(
        [TournamentType],
        [IDL.Vec(Team)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordTournamentResult' : IDL.Func([TournamentType, MatchResult], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };