/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type MatchFormat = { 'odi' : null } |
  { 't20' : null } |
  { 'test' : null };
export type MatchId = bigint;
export interface MatchResult {
  'overs' : bigint,
  'wonToss' : string,
  'runs' : bigint,
  'remainingBalls' : bigint,
  'winner' : string,
  'ballsPlayed' : bigint,
  'wickets' : bigint,
  'batFirst' : string,
}
export interface MatchState {
  'result' : [] | [MatchResult],
  'totalOvers' : bigint,
  'isOver' : boolean,
  'wicketsLost' : bigint,
  'currentOver' : bigint,
  'matchId' : MatchId,
  'runsScored' : bigint,
  'format' : MatchFormat,
}
export interface Player {
  'bowlingRating' : bigint,
  'name' : string,
  'battingRating' : bigint,
}
export interface Team {
  'name' : string,
  'countryCode' : string,
  'jerseyColor' : string,
  'squad' : Array<Player>,
}
export type TournamentType = { 'bbl' : null } |
  { 'ipl' : null } |
  { 'ranjiTrophy' : null } |
  { 'countyChampionship' : null } |
  { 'sheffieldShield' : null };
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTeam' : ActorMethod<[string, string, string, Array<Player>], undefined>,
  'addTournamentTeam' : ActorMethod<[TournamentType, Team], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearMatches' : ActorMethod<[], undefined>,
  'clearTeams' : ActorMethod<[], undefined>,
  'createMatch' : ActorMethod<
    [MatchFormat, boolean, bigint, bigint, bigint, bigint, [] | [MatchResult]],
    MatchId
  >,
  'getAllMatches' : ActorMethod<[], Array<MatchState>>,
  'getAllTeams' : ActorMethod<[], Array<Team>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[MatchId], [] | [MatchState]>,
  'getTeamByName' : ActorMethod<[string], [] | [Team]>,
  'getTournamentMatches' : ActorMethod<[TournamentType], Array<MatchResult>>,
  'getTournamentTeams' : ActorMethod<[TournamentType], Array<Team>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordTournamentResult' : ActorMethod<
    [TournamentType, MatchResult],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];